### ISSUE TITLE
ko-zh & zh-ko 

### ISSUE THREAD

**Issue by momoongithub** [themoeway/kaikki-to-yomitan#48]
Could you please add Korean-Chinese dictionary and Chinese-Korean dictionary if it is not difficult?

**Comment by StefanVukovic99** [comment]
ko-zh was missing from the [latest release](https://github.com/themoeway/kaikki-to-yomitan/releases/tag/v2024-05-31-09-23-25-00-00) for some reason, I've added it now. 

A full zh-ko is not possible yet, since the Korean Wiktionary is not available on kaikki - see https://github.com/tatuylonen/wiktextract/issues/534. There may be a small zh-ko dict based on the Chinese Wiktionary's "translations" section soon - see #46.

**Comment by momoongithub** [comment]
I get it.Thank you so much!

**Comment by StefanVukovic99** [comment]
zh-ko is now available on the [downloads](https://github.com/themoeway/kaikki-to-yomitan/blob/master/downloads.md) page (in the 3rd table)
