### ISSUE TITLE
serbo-croatian dictionary throwing error

### ISSUE THREAD

**Issue by gelbziesel** [themoeway/kaikki-to-yomitan#56]
Hello! I've tried to create some dictionaries for serbo-croatian and also to download it from the release section, but no matter which serbo-croatian (sh) dictionary I download or create, I always get this error: `ExtensionError: Dictionary has invalid data in 'index.json'`

I am using Firefox with Yomitan 24.5.21.0

I also tried a few other dictionaries from the release section and created some myself which all worked without problems, I only have issues with the serbo-croatian one.

**Comment by StefanVukovic99** [comment]
I fixed this in https://github.com/themoeway/yomitan/pull/1009, but it hasn't been included in a release yet. 
It's caused by `sh` being a deprecated ISO code so it wasn't included in our list. 

As a temporary fix, I changed the code in `index.json` to `sr`:
[kty-sr(sh)-en.zip](https://github.com/user-attachments/files/15534894/kty-sr.sh.-en.zip)
[kty-sr(sh)-en-ipa.zip](https://github.com/user-attachments/files/15534896/kty-sr.sh.-en-ipa.zip)

I think you're the first person to use the `sh` dict, any feedback is welcome!

**Comment by StefanVukovic99** [comment]
I just noticed that the dict contains accent marks, I think those will need to be handled, so stay tuned.

**Comment by StefanVukovic99** [comment]
[kty-sh-en-ipa.zip](https://github.com/user-attachments/files/15544829/kty-sh-en-ipa.zip)
[kty-sh-en.zip](https://github.com/user-attachments/files/15544830/kty-sh-en.zip)
These have the accent marks handled properly and should load without error in Yomitan 24.6.3.0 and above.
